name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install various apt dependencies
      run: sudo apt-get install libsqlite3-dev python3-pip libnghttp2-dev pkg-config libssl-dev liblua5.3-dev xxd

    - name: Install meson
      run: sudo pip3 install meson ninja

    - name: Configure Meson
      run: meson setup ${{github.workspace}}/build 

    - name: Build
      run: meson compile -C ${{github.workspace}}/build 

    - name: Test
      run: ${{github.workspace}}/build/testrunner 

    #- name: Test
    #  working-directory: ${{github.workspace}}/build
    #  # Execute tests defined by the CMake configuration.  
    #  # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
    #  run: ctest -C ${{env.BUILD_TYPE}}
      
